using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using Xunit;

namespace PropStruct.Protocol.Tests;

/// <summary>
/// Surface level (AGENTS.md §13, second table, row 1): the public surface of every library assembly of the tree
/// (the test assemblies' surface is their tests) equals the approved snapshot. A tripwire, not a contract: the
/// contract is the <c>API.md</c> of each node; the snapshot makes a change of the contract impossible to commit
/// unnoticed, because it moves in the same diff.
/// </summary>
public sealed class SurfaceTests
{
    public static string ApprovedPath => Path.Combine(Tree.Root, "tests", "Protocol.Tests", "PublicSurface.approved.txt");

    public static string ActualPath => Path.Combine(Tree.Root, "tests", "Protocol.Tests", "PublicSurface.actual.txt");

    [Fact]
    public void ThePublicSurfaceOfTheLibraryAssembliesMatchesTheApprovedSnapshot()
    {
        var assemblies = NodeAssemblies.Assemblies.Values.Where(assembly => !NodeAssemblies.IsTestAssembly(assembly)).OrderBy(assembly => assembly.GetName().Name, StringComparer.Ordinal).ToList();
        Assert.NotEmpty(assemblies);
        var actual = Describe(assemblies);
        if (!File.Exists(ApprovedPath))
        {
            File.WriteAllText(ApprovedPath, actual);
            Assert.Fail($"No approved snapshot of the public surface existed, so one was written to {ApprovedPath}. " +
                        "Read it, satisfy yourself that it is the surface the API.md of every node describes, commit it, and re-run.");
        }

        var approved = Normalise(File.ReadAllText(ApprovedPath));
        var current = Normalise(actual);
        if (approved == current)
        {
            File.Delete(ActualPath);
            return;
        }

        File.WriteAllText(ActualPath, actual);
        var approvedLines = approved.Split('\n');
        var currentLines = current.Split('\n');
        var first = Enumerable.Range(0, Math.Max(approvedLines.Length, currentLines.Length))
            .First(i => i >= approvedLines.Length || i >= currentLines.Length || approvedLines[i] != currentLines[i]);
        Assert.Fail(
            "The public surface of the library assemblies no longer matches PublicSurface.approved.txt.\n" +
            $"First difference at line {first + 1}: approved '{(first < approvedLines.Length ? approvedLines[first] : "<end>")}', " +
            $"actual '{(first < currentLines.Length ? currentLines[first] : "<end>")}'.\n" +
            $"What it is now was written to {ActualPath}. If the change is intended, update the API.md of the node that owns the type " +
            "first, then replace the approved file with the actual one in the same commit.");
    }

    /// <summary>The snapshot text: one section per assembly, one line per exported type with its kind and bases, one indented line per public member, all ordinal.</summary>
    public static string Describe(IReadOnlyList<Assembly> assemblies)
    {
        ArgumentNullException.ThrowIfNull(assemblies);

        var builder = new StringBuilder();
        _ = builder.AppendLine("# Public surface of the library assemblies of the tree.");
        _ = builder.AppendLine("# Generated by Protocol.Tests.SurfaceTests; a tripwire, not a contract: the contract is the API.md of each node.");
        _ = builder.AppendLine("# On an intended change, update that API.md and replace this file with PublicSurface.actual.txt in the same commit.");
        foreach (var assembly in assemblies)
        {
            _ = builder.AppendLine();
            _ = builder.AppendLine("== " + assembly.GetName().Name);
            foreach (var type in assembly.GetExportedTypes().OrderBy(type => type.FullName, StringComparer.Ordinal))
            {
                _ = builder.AppendLine();
                _ = builder.AppendLine(DescribeType(type));
                var members = type.GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                    .Where(IsWorthListing)
                    .Select(member => DescribeMember(type, member))
                    .Order(StringComparer.Ordinal);
                foreach (var member in members)
                {
                    _ = builder.AppendLine("    " + member);
                }
            }
        }

        return builder.ToString();
    }

    private static string DescribeType(Type type)
    {
        var kind = type.IsEnum ? "enum"
            : type.IsInterface ? "interface"
            : typeof(Delegate).IsAssignableFrom(type) ? "delegate"
            : type.IsValueType ? (type.IsDefined(typeof(IsReadOnlyAttribute), inherit: false) ? "readonly struct" : "struct")
            : type.IsAbstract && type.IsSealed ? "static class"
            : type.IsSealed ? "sealed class"
            : type.IsAbstract ? "abstract class"
            : "class";
        if (type.GetMethod("<Clone>$", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance) is not null)
        {
            kind += " (record)";
        }

        var bases = new List<string>();
        if (type.BaseType is { } baseType && baseType != typeof(object) && baseType != typeof(ValueType) && baseType != typeof(Enum) && baseType != typeof(MulticastDelegate))
        {
            bases.Add(TypeName(baseType));
        }

        bases.AddRange(type.GetInterfaces().Where(contract => contract.IsPublic || contract.IsNestedPublic).Select(contract => TypeName(contract)).Order(StringComparer.Ordinal));
        var underlying = type.IsEnum ? " : " + TypeName(Enum.GetUnderlyingType(type)) : bases.Count > 0 ? " : " + string.Join(", ", bases) : string.Empty;
        return $"{kind} {type.FullName}{underlying}";
    }

    /// <summary>
    /// Drops what the compiler wrote rather than the author: property and event accessors (reported through the
    /// property or the event), the record clone helper, the backing field of an enum, and members marked
    /// compiler-generated (the synthesized equality and printing of records). Everything else stays: operators
    /// and Deconstruct included, a caller can bind to them.
    /// </summary>
    private static bool IsWorthListing(MemberInfo member) => member switch
    {
        MethodInfo { IsSpecialName: true } method when method.Name.StartsWith("get_", StringComparison.Ordinal)
                                                       || method.Name.StartsWith("set_", StringComparison.Ordinal)
                                                       || method.Name.StartsWith("add_", StringComparison.Ordinal)
                                                       || method.Name.StartsWith("remove_", StringComparison.Ordinal) => false,
        MethodInfo { Name: "<Clone>$" } => false,
        FieldInfo { Name: "value__" } => false,
        _ => !TypeShape.IsCompilerGenerated(member),
    };

    private static string DescribeMember(Type owner, MemberInfo member) => member switch
    {
        MethodInfo method =>
            $"{(method.IsStatic ? "static " : string.Empty)}{TypeName(method.ReturnType, Nullability(method.ReturnParameter))} {method.Name}" +
            $"{GenericArguments(method)}({string.Join(", ", method.GetParameters().Select(DescribeParameter))})",
        ConstructorInfo constructor =>
            $"{(constructor.IsStatic ? "static " : string.Empty)}.ctor({string.Join(", ", constructor.GetParameters().Select(DescribeParameter))})",
        PropertyInfo property =>
            $"{(property.GetAccessors(nonPublic: true).Any(accessor => accessor.IsStatic) ? "static " : string.Empty)}" +
            $"{TypeName(property.PropertyType, Nullability(property))} " +
            (property.GetIndexParameters() is { Length: > 0 } indices
                ? $"this[{string.Join(", ", indices.Select(DescribeParameter))}]"
                : property.Name) +
            $" {{ {Getter(property)}{Setter(property)}}}",
        FieldInfo field when owner.IsEnum && field.IsLiteral =>
            $"{field.Name} = {Constant(field.GetRawConstantValue(), Enum.GetUnderlyingType(owner))}",
        FieldInfo field when field.IsLiteral =>
            $"const {TypeName(field.FieldType)} {field.Name} = {Constant(field.GetRawConstantValue(), field.FieldType)}",
        FieldInfo field =>
            $"{(field.IsStatic ? "static " : string.Empty)}{(field.IsInitOnly ? "readonly " : string.Empty)}{TypeName(field.FieldType, Nullability(field))} {field.Name}",
        EventInfo @event => $"event {TypeName(@event.EventHandlerType!)} {@event.Name}",
        Type nested => $"nested {nested.Name}",
        _ => $"{member.MemberType} {member.Name}",
    };

    private static string DescribeParameter(ParameterInfo parameter)
    {
        var modifier = parameter.IsOut ? "out "
            : parameter.IsIn ? "in "
            : parameter.ParameterType.IsByRef ? "ref "
            : parameter.IsDefined(typeof(ParamArrayAttribute), inherit: false) ? "params "
            : string.Empty;
        var name = TypeName(parameter.ParameterType, Nullability(parameter));
        var @default = parameter.HasDefaultValue ? " = " + Constant(parameter.RawDefaultValue, parameter.ParameterType) : string.Empty;
        return $"{modifier}{name} {parameter.Name}{@default}";
    }

    private static string Getter(PropertyInfo property) => property.GetMethod is { IsPublic: true } ? "get; " : string.Empty;

    /// <summary>Tells init from set: reflection reports both as writable, and the difference is the immutability the tree insists on.</summary>
    private static string Setter(PropertyInfo property)
    {
        if (property.SetMethod is not { IsPublic: true } setter)
        {
            return string.Empty;
        }

        var initOnly = setter.ReturnParameter.GetRequiredCustomModifiers().Any(modifier => modifier.FullName == "System.Runtime.CompilerServices.IsExternalInit");
        return initOnly ? "init; " : "set; ";
    }

    private static string GenericArguments(MethodInfo method) =>
        method.IsGenericMethod ? "<" + string.Join(", ", method.GetGenericArguments().Select(argument => argument.Name)) + ">" : string.Empty;

    private static readonly NullabilityInfoContext NullabilityContext = new();

    private static bool Nullability(ParameterInfo parameter) => IsNullable(NullabilityContext.Create(parameter));

    private static bool Nullability(PropertyInfo property) => IsNullable(NullabilityContext.Create(property));

    private static bool Nullability(FieldInfo field) => IsNullable(NullabilityContext.Create(field));

    private static bool IsNullable(NullabilityInfo info) =>
        !info.Type.IsValueType && (info.ReadState == NullabilityState.Nullable || info.WriteState == NullabilityState.Nullable);

    /// <summary>C#-like names: generic arguments spelled out, arrays with brackets, nullable value types with a question mark, by-reference types as their element.</summary>
    private static string TypeName(Type type, bool nullable = false)
    {
        if (type.IsByRef || type.IsPointer)
        {
            return TypeName(type.GetElementType()!) + (type.IsPointer ? "*" : string.Empty);
        }

        if (type.IsArray)
        {
            return TypeName(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
        }

        if (Nullable.GetUnderlyingType(type) is { } underlying)
        {
            return TypeName(underlying) + "?";
        }

        var name = type.IsGenericType
            ? TypeShape.SimpleName(type) + "<" + string.Join(", ", type.GetGenericArguments().Select(argument => TypeName(argument))) + ">"
            : type.IsGenericParameter ? type.Name : TypeShape.SimpleName(type);
        if (type.IsNested && !type.IsGenericParameter)
        {
            name = TypeName(type.DeclaringType!) + "." + name;
        }

        return nullable ? name + "?" : name;
    }

    private static string Constant(object? value, Type type)
    {
        if (value is null)
        {
            return "null";
        }

        if (type.IsEnum)
        {
            return Enum.ToObject(type, value).ToString()!;
        }

        return value switch
        {
            string text => "\"" + text + "\"",
            bool flag => flag ? "true" : "false",
            double number => number.ToString("R", CultureInfo.InvariantCulture),
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "f",
            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
            _ => value.ToString() ?? "null",
        };
    }

    private static string Normalise(string text) => text.ReplaceLineEndings("\n").TrimEnd();
}
