using System.Text.Json;
using PropStruct.Tests.Harness;

namespace PropStruct.Statistics.Tests;

/// <summary>
/// One shipped formulation of the survey: what the executable's own pre-loop left for it, per key of the map's
/// <c>expect</c> rows, as the binary32 bits it stored; or why the oracle could not run it.
/// </summary>
internal sealed record SurveyEntry(string Formulation, string DatSha256, string? Stop, IReadOnlyDictionary<string, ExecutedBits[]> Executed);

/// <summary>
/// One drawn JZZ = 2 loop of the survey's controls: the shares and bounds the executable was given, its <c>ZX</c>, and the
/// <c>DOKM</c> and <c>DOKSD</c> its pre-loop left, each as the bits it stored.
/// </summary>
internal sealed record Jzz2Control(double[] Shares, double[] Bounds, double[] Zx, ExecutedBits Dokm, ExecutedBits Doksd);

/// <summary>
/// The pre-loop survey (<c>tests/Fixtures/cases/statistics/preloop_survey.json</c>, generated by
/// <c>preloop_survey.py</c>), read once: the listing oracle's pre-loop run over every <c>.dat</c> the repository
/// ships, the menu at its defaults.
/// </summary>
internal static class PreloopSurvey
{
    private static readonly Lazy<JsonDocument> Document = new(() => JsonDocument.Parse(File.ReadAllText(Path)));

    private static readonly Lazy<IReadOnlyList<SurveyEntry>> LoadedEntries = new(() => Document.Value.RootElement.GetProperty("formulations")
        .EnumerateArray().Select(ReadEntry).ToList());

    private static readonly Lazy<IReadOnlyList<Jzz2Control>> LoadedControls = new(() => Document.Value.RootElement.GetProperty("jzz2Controls")
        .EnumerateArray().Select(ReadControl).ToList());

    public static string Path => RepositoryPaths.Resolve("tests", "Fixtures", "cases", "statistics", "preloop_survey.json");

    public static JsonElement Root => Document.Value.RootElement;

    public static IReadOnlyList<SurveyEntry> Entries => LoadedEntries.Value;

    /// <summary>The drawn JZZ = 2 loops: what <c>Setup.AnalyticSizes</c> is held to where no shipped formulation tells its stores apart.</summary>
    public static IReadOnlyList<Jzz2Control> Jzz2Controls => LoadedControls.Value;

    private static SurveyEntry ReadEntry(JsonElement entry)
    {
        var stop = entry.TryGetProperty("stop", out var stopped) ? stopped.GetString() : null;
        var executed = entry.TryGetProperty("preloop", out var preloop)
            ? preloop.EnumerateObject().ToDictionary(p => p.Name, p => ExecutedBits.Read(p.Value.GetProperty("executed")), StringComparer.Ordinal)
            : [];
        return new SurveyEntry(entry.GetProperty("formulation").GetString()!, entry.GetProperty("datSha256").GetString()!, stop, executed);
    }

    private static Jzz2Control ReadControl(JsonElement control) => new(
        Doubles(control.GetProperty("shares")), Doubles(control.GetProperty("bounds")),
        ExecutedBits.Read(control.GetProperty("zx")).Select(b => b.Value).ToArray(),
        ExecutedBits.Read(control.GetProperty("dokm"))[0], ExecutedBits.Read(control.GetProperty("doksd"))[0]);

    private static double[] Doubles(JsonElement array) => array.EnumerateArray().Select(e => e.GetDouble()).ToArray();
}
