using Xunit;
using Xunit.Abstractions;

namespace PropStruct.Tests.Harness.Tests;

/// <summary>
/// <c>tests/Harness/StatisticalCriterion.cs</c>, "Count floor: the boundary is judged around its own predictive
/// mean in the zero/near-zero-total regime" (defect found and fixed 2026-09-24; <c>tests/Harness/BOOT.md</c> has
/// the full measurement, including the 160-run null this test's own scenario was picked from). Proves the fix
/// red/green and adds the taboo's own required positive control (root <c>BOOT.md</c> Taboos: "every check that
/// guards a quantitative claim is proven twice").
///
/// The scenario is a real, unedited fixture cell, never a value engineered to pass: HPEPA3's own reference prints
/// <c>fqkarm[75]</c> as <c>0</c>, and so does every one of its 32 own Independent replicas, so
/// <see cref="StatisticalCriterion.Compare"/> judges this cell entirely by the count floor
/// (<see cref="CalibrationRule.Count"/>). The test reads the negative binomial's own
/// <c>[low, high]</c> boundary and quantum straight off <see cref="CellVerdict"/> — never
/// retyped or recomputed a second way here (root <c>BOOT.md</c> Taboos: no second implementation of a formula;
/// AGENTS.md §6, "a criterion with the quantifier 'all' is checked against a list generated by the machine").
///
/// ⚠ Measured red on the pre-fix code (`git diff` of the fix left uncommitted during the proof, reverted by hand
/// immediately after — the same technique <c>TwoSampleBiasOfSetsConstantCellTests</c> uses): a candidate set to
/// exactly this cell's own `RegionHigh` (3 quanta here) failed, `CriterionFailure { Quantity = fqkarm, Index = 75,
/// Value = 1.22E-08, Mean = 0, Threshold = 1.2136...E-08 }` — the candidate's own reconstructed count sat exactly
/// at the negative binomial's own upper boundary, and the pre-fix comparison (centred on the replicas' sample
/// mean, `0`, rather than the interval's own predictive mean) excluded that boundary by
/// `predictedMean * quantum`, a fixed, non-zero gap independent of any print rounding. Green after the fix, below.
/// </summary>
public sealed class CountFloorBoundaryTests
{
    private readonly ITestOutputHelper _output;

    public CountFloorBoundaryTests(ITestOutputHelper output)
    {
        _output = output;
    }

    private static Dictionary<string, double[]> CloneReference(string formulation) =>
        new(ResultsMFile.Parse(RepositoryPaths.Resolve("tests", "Fixtures", "references", formulation, "results.m.txt")));

    private const string Formulation = "HPEPA3";
    private const ReplicaKind Kind = ReplicaKind.Independent;
    private const string Quantity = "fqkarm";
    private const int Index = 75;

    private static CriterionReport CompareWithCellSetTo(string formulation, IReadOnlyDictionary<string, double[]> baseCandidate, ReplicaKind kind, string quantity, int index, double value)
    {
        var candidate = new Dictionary<string, double[]>(baseCandidate);

        // The reference's own printed `fqkarm` stops before index 75 (a trailing run of exact zeros is never
        // printed, this node's BOOT.md, ## Invariants, "Cells absent from an array ... compare as 0"); `Compare`
        // already reads that missing tail as 0.0 for every source, so growing the array here to explicitly carry
        // `value` at `index` changes nothing this criterion does not already treat as equivalent to the missing
        // tail, and lets a real value be placed exactly where the missing-tail convention already put an
        // implicit 0.
        var array = candidate[quantity].Length > index
            ? (double[])candidate[quantity].Clone()
            : new double[index + 1];
        Array.Copy(candidate[quantity], array, candidate[quantity].Length);
        array[index] = value;
        candidate[quantity] = array;
        return StatisticalCriterion.Compare(formulation, candidate, kind);
    }

    // A source's own missing tail past its printed length reads as 0.0 (this node's BOOT.md, ## Invariants,
    // "Cells absent from an array ... compare as 0"), the same convention `Compare` itself applies.
    private static double ValueOrZero(double[] array, int index) => index < array.Length ? array[index] : 0.0;

    [Fact]
    public void CandidateExactlyAtTheCountFloorsOwnUpperBoundaryPassesAndBeyondItStillFails()
    {
        var reference = CloneReference(Formulation);
        Assert.Equal(0.0, ValueOrZero(reference[Quantity], Index));
        for (var k = 1; k <= ResultsMFileTests.Formulations.Single(f => f.Name == Formulation).ReplicaCount; k++)
        {
            var replica = ResultsMFile.Parse(RepositoryPaths.Resolve("tests", "Fixtures", "replicas-independent", Formulation, k + ".m.txt"));
            Assert.Equal(0.0, ValueOrZero(replica[Quantity], Index));
        }

        // The cell's own quantum and the negative binomial's own upper boundary, read live off the current
        // code — never typed by hand (AGENTS.md §6, the "quantifier 'all'" rule applies equally to a single
        // machine-computed figure the test would otherwise have to retype).
        var baselineReport = StatisticalCriterion.Compare(Formulation, reference, Kind);
        var alpha = StatisticalCriterion.Alpha / Math.Max(baselineReport.Compared, 1);
        var baselineVerdict = StatisticalCriterion.CompareCellVerdicts(Formulation, reference, Kind, alpha)
            .Single(v => v.Name == Quantity && v.Index == Index);

        Assert.Equal(CalibrationRule.Count, baselineVerdict.Rule);
        Assert.False(baselineVerdict.Failed);
        var regionHigh = Assert.IsType<double>(baselineVerdict.RegionHigh);
        var quantum = Assert.IsType<double>(baselineVerdict.Quantum);
        _output.WriteLine(
            $"{Formulation} {Kind} {Quantity}[{Index}]: quantum={quantum:G9} regionHigh={regionHigh:G9} " +
            $"({regionHigh / quantum:G6} quanta).");

        // Green (the fix): a candidate reconstructing to exactly the negative binomial's own `high` — this
        // node's BOOT.md, ## Invariants, "Count-like cells": the interval keeps `P(X <= high) >= 1 - alpha/2`,
        // i.e. `high` itself is inside it — must not fail.
        var atBoundary = CompareWithCellSetTo(Formulation, reference, Kind, Quantity, Index, regionHigh);
        Assert.DoesNotContain(atBoundary.Failures, f => f.Quantity == Quantity && f.Index == Index);

        // Red / positive control (root BOOT.md Taboos, "every check ... is proven twice"): one whole quantum
        // past `high` must still fail — the fix only recentres the comparison, it never widens `countFloor`
        // itself, so a candidate genuinely outside the interval is unaffected.
        var oneQuantumPast = CompareWithCellSetTo(Formulation, reference, Kind, Quantity, Index, regionHigh + quantum);
        Assert.Contains(oneQuantumPast.Failures, f => f.Quantity == Quantity && f.Index == Index);

        // A second, larger positive control (the task's own instruction: "many quanta, e.g. 20"): still fails.
        var twentyQuantaPast = CompareWithCellSetTo(Formulation, reference, Kind, Quantity, Index, regionHigh + 20.0 * quantum);
        Assert.Contains(twentyQuantaPast.Failures, f => f.Quantity == Quantity && f.Index == Index);
    }
}
