using ILGPU.Runtime;
using PropStruct.Random;
using PropStruct.Statistics;
using PropStruct.Tests.Harness;
using Xunit;

namespace PropStruct.Particle.Tests;

/// <summary>
/// Checks <see cref="Attempt.Run"/>'s own <see cref="PrecisionKind.Original"/> rounding,
/// by its actually observed behaviour, against the write-site mapping
/// <c>src/Particle/RealFourWriteSites.txt</c> (root BOOT.md, "Precision kind is an
/// option of every run"; that node's BOOT.md, "Accumulators", "Design decision,
/// 2026-09-24: the membership is generated too, not only the kind").
///
/// Running the identical attempt sequence twice, once per <see cref="PrecisionKind"/>,
/// and diffing the two resulting records is a behavioural check of <c>Attempt.cs</c>'s real
/// code, not a second, independently-typed copy of the classification standing beside it
/// (AGENTS.md §6, "a criterion quantified by 'all'... checked against a list generated by
/// the machine"): a field a "ported: &lt;field&gt;" mapping row names must differ between
/// the two runs somewhere it was actually touched, and a field no such row names (a
/// real*8-declared field) must be bit-identical everywhere it was touched. No
/// REAL*4-classified <see cref="AccumulatorLayout"/> field is ever read back inside
/// <see cref="Attempt.Run"/> (BOOT.md's own "Accumulators" line map: every rounded field is
/// write-only within the attempt), so the kind cannot change a decision, a draw or an
/// outcome -- the two runs draw the identical sequence of neighbours and take the identical
/// branches, and only the rounded cells' own bits can differ. That is what makes running
/// the sequence twice, rather than once with a shadow accumulator, a direct test of the
/// real code path instead of a parallel model of it.
/// </summary>
public class PrecisionKindClassificationTests
{
    // Large enough that every one of the fifteen rounded fields and all twelve excluded
    // fields is touched at least once on HPEPA3 (asserted below, not assumed); small enough
    // that this stays in the fast set (a plain, un-batched loop of direct Attempt.Run calls,
    // no kernel launch -- ILGPU CPU accelerator buffers only for the ArrayView plumbing).
    private const int Cycle0Attempts = 4_000;
    private const int Cycle1Attempts = 12_000;

    /// <summary>
    /// Reads <c>RealFourWriteSites.txt</c>'s own "ported: &lt;identifier&gt;" rows
    /// (AGENTS.md §6: the rounding set is generated -- by
    /// <c>classify-real4-accumulators.py</c> -- and cross-checked against this
    /// hand-written write-site mapping by
    /// <c>tests/Particle.Tests/RealFourAccumulatorMappingTests.cs</c>, not re-derived
    /// here) for the subset of "ported" identifiers that name an
    /// <see cref="AccumulatorLayout"/> record field: an <see cref="AccumulatorLayout"/>
    /// field named there is expected to round under <see cref="PrecisionKind.Original"/>;
    /// every other field of <see cref="RecordFields"/> (a real*8-declared field, by
    /// <c>RealFourAccumulators.generated.txt</c>'s own absence of a row for its Fortran
    /// name) is expected not to.
    /// </summary>
    private static HashSet<string> ParsePortedFieldNames()
    {
        var path = RepositoryPaths.Resolve("src", "Particle", "RealFourWriteSites.txt");
        var portedIdentifiers = new HashSet<string>();
        foreach (var line in File.ReadAllLines(path))
        {
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            var cells = line.Split('|', 2);
            Assert.True(cells.Length == 2, $"malformed write-site row: {line}");
            var disposition = cells[1].Trim();
            if (disposition.StartsWith("ported:", StringComparison.Ordinal))
            {
                _ = portedIdentifiers.Add(disposition["ported:".Length..].Trim());
            }
        }

        Assert.NotEmpty(portedIdentifiers);
        return portedIdentifiers;
    }

    /// <summary>
    /// Offset and length of every <see cref="AccumulatorLayout"/> record field, in the
    /// accumulator's own units (API.md, "Accumulator layout"). <c>Fmkarm2Loc</c> is the
    /// scratch array, not a record offset, and is not tested here: <see cref="RunRecord"/>
    /// reads back only <c>record</c>, and its own last-attempt value is reset every attempt
    /// (BOOT.md, "Accumulators"), so it is checked by
    /// <c>tests/Particle.Tests/RealFourAccumulatorMappingTests.cs</c>'s write-site check
    /// instead, not by a behavioural diff.
    /// </summary>
    private static readonly (string Field, Func<AccumulatorLayout, int> Offset, Func<ModelSetup, int> Length)[] RecordFields =
    {
        ("Xss", l => l.Xss, _ => 7),
        ("DokBase41", l => l.DokBase41, _ => 1),
        ("DokBase31", l => l.DokBase31, _ => 1),
        ("DokSur41", l => l.DokSur41, _ => 1),
        ("DokSur31", l => l.DokSur31, _ => 1),
        ("Sd4", l => l.Sd4, _ => 1),
        ("Sd3", l => l.Sd3, _ => 1),
        ("D41", l => l.D41, _ => 1),
        ("D31", l => l.D31, _ => 1),
        ("Dp31", l => l.Dp31, _ => 1),
        ("Dp41", l => l.Dp41, _ => 1),
        ("JammedTotal", l => l.JammedTotal, _ => 1),
        ("NnTotal", l => l.NnTotal, _ => 1),
        ("VmkmTotal2", l => l.VmkmTotal2, _ => 1),
        ("VdokTotal2", l => l.VdokTotal2, _ => 1),
        ("Allvdok", l => l.Allvdok, s => s.Ndok),
        ("Vdokstr", l => l.Vdokstr, s => s.Ndok),
        ("Vsmkm", l => l.Vsmkm, s => s.Ndok),
        ("Svd", l => l.Svd, s => s.Ndok),
        ("VmkmTotal", l => l.VmkmTotal, s => s.Ndok),
        ("VdokTotal", l => l.VdokTotal, s => s.Ndok),
        ("Vks", l => l.Vks, s => s.Nkarm),
        ("FmkarmCor", l => l.FmkarmCor, s => s.Nkarm),
        ("Fmkarm2", l => l.Fmkarm2, s => s.Nkarm),
        ("Dokp41", l => l.Dokp41, s => s.Ncat),
        ("Dokp31", l => l.Dokp31, s => s.Ncat),
    };

    /// <summary>
    /// Runs the same <see cref="Cycle0Attempts"/>-then-<see cref="Cycle1Attempts"/> attempt
    /// sequence <see cref="AccumulatorSweep"/> itself runs (cycle 0 builds a real Qks
    /// histogram, cycle 1 normalizes it into Qks1 and refreshes it exactly where reference
    /// mode would, <c>pdoksmall</c> left at zero -- that class's own remarks explain why this
    /// only enlarges which branches get exercised, never assumes a result), under one
    /// <paramref name="kind"/>, and returns the final <c>record</c> and <c>scratch</c> (for
    /// <c>Fmkarm2Loc</c>'s own last-attempt value, which is reset every attempt so only the
    /// final attempt's own cells are informative on their own -- <see cref="Fmkarm2"/> in
    /// <paramref name="record"/> is the field this test actually reads for that accumulator,
    /// see below). Never resets <c>record</c> between accepted particles (unlike reference
    /// mode): this test wants one attempt sequence's whole accumulation, not per-particle
    /// folding, which is <see cref="Fold"/>'s own concern, checked elsewhere.
    /// </summary>
    private static double[] RunRecord(Accelerator accelerator, ModelSetup setup, PrecisionKind kind, SetupTablesBuffers tables)
    {
        setup.Kind = kind;
        var layout = setup.Layout;

        using var integerTotals = accelerator.Allocate1D<long>(layout.IntegerLength);
        integerTotals.MemSetToZero();
        using var record = accelerator.Allocate1D<double>(layout.RecordLength);
        record.MemSetToZero();
        using var scratch = accelerator.Allocate1D<double>(layout.ScratchLength);
        scratch.MemSetToZero();

        var fractions = tables.Fractions;
        var streams = OriginalSeeds.Streams;

        var cycleZero = new CycleInputs { CycleFlag = 0, Dmaxxx = 0.0, Qks1 = default, Pdoksmall = default };
        for (var i = 0; i < Cycle0Attempts; i++)
        {
            _ = Attempt.Run(setup, fractions, cycleZero, ref streams, integerTotals.View.BaseView, record.View.BaseView, scratch.View.BaseView);
        }

        using var qks1 = accelerator.Allocate1D<double>(setup.Nkarm);
        PocketHistogram.Normalize(layout, integerTotals.View.BaseView, qks1.View.BaseView);
        using var pdoksmall = accelerator.Allocate1D<double>(setup.Ndok);
        pdoksmall.MemSetToZero();

        var cycleOne = new CycleInputs { CycleFlag = 1, Dmaxxx = 1e30, Qks1 = qks1.View.BaseView, Pdoksmall = pdoksmall.View.BaseView };

        var loopCompletionsBefore = 0L;
        for (var i = 0; i < Cycle1Attempts; i++)
        {
            _ = Attempt.Run(setup, fractions, cycleOne, ref streams, integerTotals.View.BaseView, record.View.BaseView, scratch.View.BaseView);

            var totalsNow = integerTotals.GetAsArray1D();
            var loopCompletionsAfter = totalsNow[layout.LoopCompletions];
            if (loopCompletionsAfter != loopCompletionsBefore)
            {
                PocketHistogram.Normalize(layout, integerTotals.View.BaseView, qks1.View.BaseView);
                loopCompletionsBefore = loopCompletionsAfter;
            }
        }

        return record.GetAsArray1D();
    }

    private readonly record struct SetupTablesBuffers(FractionTable Fractions, IDisposable[] Owned);

    private static SetupTablesBuffers BuildFractions(Accelerator accelerator, SetupTables tables)
    {
        var bounds = accelerator.Allocate1D(tables.Bounds);
        var cumulative = accelerator.Allocate1D(tables.Cumulative);
        var forming = accelerator.Allocate1D(tables.PocketForming);
        var fractions = new FractionTable
        {
            Bounds = bounds.View.BaseView,
            Cumulative = cumulative.View.BaseView,
            PocketForming = forming.View.BaseView,
        };
        return new SetupTablesBuffers(fractions, new IDisposable[] { bounds, cumulative, forming });
    }

    [Fact]
    public void RoundingSetMatchesTheGeneratedClassification()
    {
        var portedFieldNames = ParsePortedFieldNames();

        using var host = new CpuHost();
        var setup = ReferenceFormulation.Prepare(host.Accelerator, "HPEPA3", out var tables, out _);
        var tableBuffers = BuildFractions(host.Accelerator, tables);
        try
        {
            var binary64Record = RunRecord(host.Accelerator, setup, PrecisionKind.Binary64, tableBuffers);
            var originalRecord = RunRecord(host.Accelerator, setup, PrecisionKind.Original, tableBuffers);

            var untouched = new List<string>();
            var wronglyIdentical = new List<string>();
            var wronglyDifferent = new List<string>();

            foreach (var (field, offsetFn, lengthFn) in RecordFields)
            {
                var expectedRounds = portedFieldNames.Contains(field);

                var offset = offsetFn(setup.Layout);
                var length = lengthFn(setup);

                var touched = false;
                var differsSomewhere = false;
                for (var c = 0; c < length; c++)
                {
                    var a = binary64Record[offset + c];
                    var b = originalRecord[offset + c];
                    if (a != 0.0 || b != 0.0)
                    {
                        touched = true;
                    }

                    if (a != b)
                    {
                        differsSomewhere = true;
                    }
                }

                if (!touched)
                {
                    untouched.Add(field);
                    continue;
                }

                if (expectedRounds && !differsSomewhere)
                {
                    wronglyIdentical.Add(field);
                }
                else if (!expectedRounds && differsSomewhere)
                {
                    wronglyDifferent.Add(field);
                }
            }

            Assert.True(untouched.Count == 0,
                $"the sample never touched: {string.Join(", ", untouched)} -- raise Cycle0Attempts/Cycle1Attempts, " +
                "this check cannot tell rounded from unrounded for a field it never wrote.");
            Assert.True(wronglyIdentical.Count == 0,
                $"classified 'yes' (rounds) but Binary64 and Original produced bit-identical output: {string.Join(", ", wronglyIdentical)}");
            Assert.True(wronglyDifferent.Count == 0,
                $"classified 'no' (excluded) but Binary64 and Original disagreed: {string.Join(", ", wronglyDifferent)}");
        }
        finally
        {
            foreach (var owned in tableBuffers.Owned)
            {
                owned.Dispose();
            }
        }
    }

    /// <summary>
    /// The default <see cref="ModelSetup"/> (an unset <see cref="ModelSetup.Kind"/>, as every
    /// caller built before this option existed still produces) behaves exactly as
    /// <see cref="PrecisionKind.Binary64"/>: root BOOT.md's own "Binary64 is the default".
    /// </summary>
    [Fact]
    public void UnsetKindBehavesAsBinary64()
    {
        using var host = new CpuHost();
        var setup = ReferenceFormulation.Prepare(host.Accelerator, "HPEPA3", out var tables, out _);
        Assert.Equal(default, setup.Kind);
        var tableBuffers = BuildFractions(host.Accelerator, tables);
        try
        {
            var unset = RunRecord(host.Accelerator, setup, default, tableBuffers);
            var explicitBinary64 = RunRecord(host.Accelerator, setup, PrecisionKind.Binary64, tableBuffers);
            Assert.Equal(explicitBinary64, unset);
        }
        finally
        {
            foreach (var owned in tableBuffers.Owned)
            {
                owned.Dispose();
            }
        }
    }
}
