using System.Globalization;

namespace PropStruct.Tests.Harness;

/// <summary>
/// Computes the dispersion table `tests/Harness/HISTORY.md#fable-5-1-decision-v`, item 2(d), and
/// <c>tests/Fixtures/API.md</c>, "## Dispersion table" describe: a report on <see cref="StatisticalCriterion"/>'s
/// own <see cref="CountReconstruction.ArrayTotals"/>/<see cref="DispersionEstimator.Estimate"/>,
/// never a second implementation of either. Shared by <c>tests/Harness.Tests/DispersionApprovedTests</c> (the
/// check, <c>MatchesTheCommittedTable</c>, run every full test pass) and <c>tests/DispersionTool</c> (the manual
/// generator that writes <c>tests/Fixtures/dispersion.approved.txt</c>) — one implementation of the table, not
/// one per caller (root BOOT.md Taboos).
///
/// ⚠ 2026-09-25: moved here from <c>tests/Harness.Tests/DispersionApprovedTests.cs</c>, where
/// <c>ComputeTable</c>/<c>AppendLine</c> were private and <c>Regenerate</c> was a
/// <c>[Fact(Skip = "manual regeneration only")]</c> test — a permanently skipped test, which AGENTS.md §13
/// forbids. The formulation list below is the same five names and replica counts
/// <c>tests/Harness.Tests/ResultsMFileTests.Formulations</c> and <see cref="StatisticalCriterion"/>'s own
/// (private) replica-count table already carry; not unified with either here; both those neighbours own their
/// own local reasons to keep their own copy that this move does not disturb.
/// </summary>
internal static class DispersionTable
{
    private static readonly (string Name, int ReplicaCount)[] Formulations =
    [
        ("HPEPA3", 32),
        ("inpt", 16),
        ("P33", 16),
        ("PSAN02n", 16),
        ("HMX", 16),
    ];

    private static readonly string[] FixedFamilies = ["fqkarm", "fqkarm_cor", "fqmkm1", "fqmkm2", "coef"];

    public static List<string> Compute()
    {
        var lines = new List<string>
        {
            "# Generated by tests/DispersionTool (DispersionEstimator.Estimate).",
            "# A tripwire, not a contract (AGENTS.md §13): nothing in Compare reads this file back.",
            "# formulation family/row runs groups n_bar phi rho_hat rho_hat_spread route",
        };

        foreach (var (formulation, replicaCount) in Formulations)
        {
            var referencePath = RepositoryPaths.Resolve("tests", "Fixtures", "references", formulation, "results.m.txt");
            var referenceCells = ResultsMFile.ParseCells(referencePath);
            var referenceDkarmcat = referenceCells.TryGetValue("Dkarmcat", out var rd) ? rd : [];

            var replicaCells = new List<IReadOnlyDictionary<string, ResultCell[]>>(replicaCount);
            var replicaDkarmcatMatch = new List<int>(replicaCount);
            for (var k = 1; k <= replicaCount; k++)
            {
                var path = RepositoryPaths.Resolve("tests", "Fixtures", "replicas-lagged", formulation, k + ".m.txt");
                var cells = ResultsMFile.ParseCells(path);
                replicaCells.Add(cells);
                var replicaDkarmcat = cells.TryGetValue("Dkarmcat", out var d) ? d : [];
                var matchLength = 0;
                while (matchLength < replicaDkarmcat.Length && matchLength < referenceDkarmcat.Length &&
                       replicaDkarmcat[matchLength].Value == referenceDkarmcat[matchLength].Value)
                {
                    matchLength++;
                }

                replicaDkarmcatMatch.Add(matchLength);
            }

            foreach (var family in FixedFamilies)
            {
                AppendLine(lines, formulation, family, replicaCells);
            }

            var dokRowNames = new SortedSet<string>(StringComparer.Ordinal);
            foreach (var cells in replicaCells)
            {
                foreach (var key in cells.Keys)
                {
                    if (key.StartsWith("fqdokkarm(", StringComparison.Ordinal))
                    {
                        _ = dokRowNames.Add(key);
                    }
                }
            }

            foreach (var rowName in dokRowNames)
            {
                var rowIndex0 = int.Parse(rowName[10..^3], CultureInfo.InvariantCulture) - 1;
                var eligible = new List<IReadOnlyDictionary<string, ResultCell[]>>();
                for (var r = 0; r < replicaCells.Count; r++)
                {
                    if (replicaDkarmcatMatch[r] > rowIndex0)
                    {
                        eligible.Add(replicaCells[r]);
                    }
                }

                AppendLine(lines, formulation, rowName, eligible);
            }
        }

        return lines;
    }

    private static void AppendLine(
        List<string> lines, string formulation, string arrayName, IReadOnlyList<IReadOnlyDictionary<string, ResultCell[]>> replicaCells)
    {
        var totals = CountReconstruction.ArrayTotals(replicaCells, arrayName);
        var estimate = DispersionEstimator.Estimate(replicaCells, arrayName, totals);
        if (estimate is not { } d)
        {
            return;
        }

        var route = d.Phi < 1.0 ? "student-on-count" : "beta-binomial";
        var spread = d.RhoHatSpread is { } s ? s.ToString("G6") : "-";
        lines.Add(
            $"{formulation} {arrayName} {d.Runs} {d.Groups} {d.NBar:G6} {d.Phi:G6} {d.RhoHat:G6} {spread} {route}");
    }
}
